/**
 * FeedbackBackend — the interface core UI talks to instead of hard-coding
 * `/api/feedback/...` fetch calls.
 *
 * Consumer apps pass an implementation of this interface as a prop to
 * <FeedbackChat /> and <FeedbackIssuesPage />. The launcher package provides
 * a browser-friendly default implementation that issues fetch() calls against
 * the host app's /api/feedback route handlers (which are generated by the
 * launcher package's handleFeedback* functions).
 *
 * No fallbacks: every method must be implemented by the backend. If the
 * backend is missing, the UI fails loudly rather than silently degrading.
 */

import type { ChatIssue, ChatSubmitResult } from './shared-ui';
import type { Issue } from './issues-page-types';

/** Outbound message to start or continue a clarifier chat. */
export interface SendChatMessageRequest {
  message: string;
  /** Existing session (active tmux) */
  sessionId?: string | null;
  tmuxSession?: string | null;
  /** Resume a previous session whose tmux has exited */
  resumeSessionId?: string | null;
  pagePath?: string;
  pageContext?: string;
  /** Override which app the issues target (e.g. from /feedback-lib-issues?app=foo) */
  app?: string;
  /** Optional prior-issue context passed when reopening a conversation */
  priorIssue?: {
    issueNumber?: number;
    title?: string;
    description?: string;
    status?: string;
    insights?: string;
  };
}

export interface SendChatMessageResponse {
  response: string;
  sessionId: string;
  tmuxSession: string;
  /** Proposed issues extracted from the model's reply */
  issues?: ChatIssue[];
  hookWarning?: string;
}

export class BackendAuthExpiredError extends Error {
  code = 'auth_expired' as const;
  constructor(message = 'Authentication expired') {
    super(message);
    this.name = 'BackendAuthExpiredError';
  }
}

export class BackendSessionExpiredError extends Error {
  code = 'session_expired' as const;
  constructor(message = 'Session expired') {
    super(message);
    this.name = 'BackendSessionExpiredError';
  }
}

/** Body for POST /api/feedback/issues routed through the backend. */
export type IssueAction =
  | { action: 'create'; title: string; description?: string; pagePath?: string; pageContext?: string; app?: string }
  | { action: 'update'; issueNumber: number; title?: string; description?: string; status?: string; insights?: string; labels?: string[]; app?: string }
  | { action: 'close'; issueNumber: number; app?: string }
  | { action: 'reopen'; issueNumber: number; app?: string }
  | { action: 'delete'; issueNumber: number; app?: string }
  | {
      action: 'fix';
      issues: Array<{ number: number; title: string; status?: string; insights?: string; claudeSessionIds?: string[]; claudeLaunchDir?: string }>;
      resumeSessionId?: string;
      app?: string;
    }
  | {
      action: 'reviewed';
      issueNumbers: number[];
      conclude?: boolean;
      claudeSessionId?: string;
      claudeLaunchDir?: string;
      app?: string;
    }
  | {
      action: 'maintenance';
      skill: string;
      title?: string;
      app?: string;
    };

export interface CreateIssueResult {
  ok: true;
  issueNumber: number;
  effectiveApp?: string;
}

export interface FixResult {
  ok: true;
  claudeSessionId: string;
  tmuxSession: string;
}

export interface MaintenanceResult {
  ok: true;
  claudeSessionId: string;
  tmuxSession: string;
  issueNumber?: number;
}

export interface ReviewedResult {
  ok: true;
  results: Array<{ issueNumber: number; ok: boolean; error?: string }>;
}

export interface GenericOkResult {
  ok: true;
}

export type IssueActionResult =
  | CreateIssueResult
  | FixResult
  | MaintenanceResult
  | ReviewedResult
  | GenericOkResult;

/** Message returned from the session-history endpoint for a prior clarifier chat. */
export interface HistoryMessage {
  role: string;
  text: string;
  staleIssues?: { title: string; description: string }[];
}

export interface SessionHistoryResult {
  messages: HistoryMessage[];
  found: boolean;
}

export interface ListIssuesResult {
  issues: Issue[];
  appName: string;
}

/**
 * Backend contract. Every method must be provided; if the consumer app can't
 * satisfy one, that's a setup error, not a runtime fallback.
 */
export interface FeedbackBackend {
  /** Send a message to the clarifier. Either starts a new session or continues
   *  an existing one depending on the fields in the request. */
  sendChatMessage(request: SendChatMessageRequest): Promise<SendChatMessageResponse>;

  /** Submit a set of chat-proposed issues to the tracker. */
  submitChatIssues(
    issues: ChatIssue[],
    context: { pagePath?: string; pageContext?: string; sessionId?: string | null; app?: string },
  ): Promise<ChatSubmitResult[]>;

  /** Check whether a clarifier tmux is still alive. */
  getSessionStatus(tmuxSession: string): Promise<{ alive: boolean }>;

  /** End a clarifier session (kills tmux, cleans up tmp files). */
  closeSession(tmuxSession: string): Promise<void>;

  /** Fire-and-forget variant used in `beforeunload` handlers. Implementations
   *  should use navigator.sendBeacon or an equivalent non-blocking primitive. */
  closeSessionOnUnload(tmuxSession: string): void;

  /** List issues for the app (optionally overridden by `appOverride`). */
  listIssues(appOverride?: string | null): Promise<ListIssuesResult>;

  /** Execute an issue-level action (close, reopen, update, fix, etc.). */
  issueAction(body: IssueAction): Promise<IssueActionResult>;

  /** Fetch prior clarifier chat history for resume-into-modal flows. */
  getSessionHistory(sessionId: string, appOverride?: string | null): Promise<SessionHistoryResult>;
}
