import type { MaintenancePrompt } from './issues-page-types';

export const MAINTENANCE_PROMPTS: MaintenancePrompt[] = [
  {
    id: "feedback-context",
    title: "Add feedback context tracking",
    description: "Ensure tab/section navigation sets data-active-tab on the active element so the feedback widget tracks which view the user is on.",
    prompt: "Scan this app for tab or section navigation (tab bars, sidebars, segmented controls). For each one, ensure the currently active element has a `data-active-tab` attribute set to the visible label text. This attribute must move with the active state — only the active element should have it at any given time. The feedback-lib widget reads this via `document.querySelector('[data-active-tab]')` at issue-report time. Do not remove any existing attributes. Commit and push when done.",
  },
  {
    id: "assign-data-ids",
    title: "Assign data-id to all significant UI elements",
    description: "Scan for interactive elements AND significant non-interactive UI sections missing a data-id attribute and add appropriate values.",
    prompt: "Scan all React components in this app and add a `data-id` attribute to EVERY HTML element that does not already have one. The goal is total coverage — every `<div>`, `<span>`, `<section>`, `<p>`, `<h1>`–`<h6>`, `<img>`, `<a>`, `<button>`, `<input>`, `<ul>`, `<ol>`, `<li>`, `<table>`, `<tr>`, `<td>`, `<form>`, `<label>`, `<pre>`, `<code>`, `<nav>`, `<header>`, `<footer>`, `<aside>`, `<main>`, `<article>`, and any other rendered HTML element must have a `data-id`.\n\n**No element is too small or too insignificant to skip.** This includes:\n- Wrapper divs, layout containers, grid cells, flex children\n- Individual list items, table rows, table cells\n- Image containers, screenshot preview boxes, figure/figcaption elements\n- Instruction steps, code blocks, callout boxes, alert banners\n- Loading spinners, empty states, error messages, badges, progress bars\n- Modal overlays, dialog backdrops, tooltip containers\n- Icon wrappers with semantic meaning\n- Conditionally rendered elements (ternaries, `&&` guards)\n\n**Rules:**\n1. Use descriptive kebab-case values (e.g. `data-id=\"save-settings\"`, `data-id=\"billing-summary-card\"`, `data-id=\"step-3-instructions\"`).\n2. For elements in a loop/map, include a dynamic key (e.g. `data-id={\\`app-card-${slug}\\`}`, `data-id={\\`step-${index}\\`}`, `data-id={\\`row-${id}\\`}`).\n3. Do not modify elements that already have a `data-id`.\n4. Follow imports — when a component renders a sub-component from another file, open that file and tag its elements too.\n5. Pure layout wrappers that only exist for CSS (e.g. a flex spacer div) still get a `data-id` — use a name like `data-id=\"layout-spacer\"` or `data-id=\"flex-wrapper\"`.\n\n**Completeness check**: After all files are tagged, run `grep -c 'data-id' <file>` on every component file (.tsx/.jsx). Also count the total HTML elements per file and compare. Flag any file where the counts don't match (elements without `data-id` remain) and fix before committing. Commit and push when done.",
  },
  {
    id: "refactor-large-files",
    title: "Refactor large files",
    description: "Scan for large code files and refactor them by splitting into smaller files or extracting shared utilities.",
    prompt: "Scan all source files in this app (TypeScript, TSX, JS, JSX) and identify files that are excessively large (roughly 300+ lines). For each large file, use your judgment to refactor it in one or more of these ways:\n\n1. **Split into smaller files**: If the file contains multiple distinct components, functions, or logical sections, extract them into separate files and update imports.\n2. **Extract shared utilities**: If you find repeated logic across the file (or across multiple files), extract it into a shared utility module.\n3. **Separate types/interfaces**: If the file has large type definitions, move them to a dedicated types file.\n\nPrioritize readability and maintainability. A file is only exempt from splitting if it is truly cohesive — one focused responsibility that would genuinely become harder to follow if separated. A single React component is NOT automatically cohesive: if it contains multiple distinct dialog/modal overlays, multiple independent state groups (e.g. 10+ useState hooks for separate features), or inline sub-features that could be their own component, it should be split. When in doubt, split. Skip test files, generated files, and config files. Commit and push when done.",
  },
];
